apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursemit-app-back-deployment
spec:
  selector:
   matchLabels:
    app: coursemit-app-back
  replicas: 1
  template:
    metadata:
      labels:
        app: coursemit-app-back
    spec:
      containers:
        - name: coursemit-app-back
          image: alexmejiaarias/coursemit-back
          ports:
            - containerPort: 8084
              name: coursemitback
---
apiVersion: v1
kind: Service
metadata:
  name: coursemit-app-back-service
  labels:
    app: coursemit-app-back
spec:
  selector:
   app: coursemit-app-back
  type: LoadBalancer  
  ports:
   - port: 8084
     nodePort: 30101
